Fix permissions and formatting
This change will fix git hooks scripts permissions to allow
execution.

This will also default to 4-spaces identation for scripts files.

diff --git a/git/puppet-git-hooks/pre-commit b/git/puppet-git-hooks/pre-commit
--- a/git/puppet-git-hooks/pre-commit
+++ b/git/puppet-git-hooks/pre-commit
@@ -21,11 +21,11 @@ done
 
 # Figure out where commit hooks are
 if [[ ! -z "$hook_symlink" ]] && ! [[ "$hook_symlink" == ../* ]]; then
-  #pre-commit is setup as a symlink
-  subhook_root="$(dirname "$hook_symlink")/commit_hooks"
+    #pre-commit is setup as a symlink
+    subhook_root="$(dirname "$hook_symlink")/commit_hooks"
 else
-  #commit_hooks should be with pre-commit
-  subhook_root="${hook_dir}/commit_hooks"
+    #commit_hooks should be with pre-commit
+    subhook_root="${hook_dir}/commit_hooks"
 fi
 
 # If using submodules, we need to read proper subhook root
@@ -50,7 +50,7 @@ fi
 
 # Only puppet 3.2.1 - 3.8 support "--parser future" option.
 case $(puppet --version) in
-  4*) USE_PUPPET_FUTURE_PARSER="disabled" ;;
+    4*) USE_PUPPET_FUTURE_PARSER="disabled" ;;
 esac
 
 SAVEIFS=$IFS
@@ -131,15 +131,15 @@ for changedfile in $files_to_check; do
     if [[ "$CHECK_PUPPET_LINT" != "disabled" ]] ; then
         if type puppet-lint >/dev/null 2>&1; then
             if echo "$changedfile" | grep -iq '\.pp$'; then
-              if [[ "$failures" -eq 0 ]]; then
-                ${subhook_root}/puppet_lint_checks.sh "$CHECK_PUPPET_LINT" "$changedfile"
-                RC=$?
-                if [[ "$RC" -ne 0 ]]; then
-                    failures=$((failures + 1))
+                if [[ "$failures" -eq 0 ]]; then
+                    ${subhook_root}/puppet_lint_checks.sh "$CHECK_PUPPET_LINT" "$changedfile"
+                    RC=$?
+                    if [[ "$RC" -ne 0 ]]; then
+                        failures=$((failures + 1))
+                    fi
+                else
+                    echo "Skipping puppet-lint check due to prior errors."
                 fi
-              else
-                echo "Skipping puppet-lint check due to prior errors."
-              fi
             fi
         else
             echo "puppet-lint not installed. Skipping puppet-lint tests..."
@@ -150,26 +150,26 @@ IFS=$SAVEIFS
 
 #rspec test validation
 if [[ "$CHECK_RSPEC" != "disabled" ]] ; then
-  if hash rspec >/dev/null 2>&1; then
-      ${subhook_root}/rspec_puppet_checks.sh
-      RC=$?
-      if [[ "$RC" -ne 0 ]]; then
-          failures=$((failures + 1))
-      fi
-  else
-      echo "rspec not installed. Skipping rspec-puppet tests..."
-  fi
+    if hash rspec >/dev/null 2>&1; then
+        ${subhook_root}/rspec_puppet_checks.sh
+        RC=$?
+        if [[ "$RC" -ne 0 ]]; then
+            failures=$((failures + 1))
+        fi
+    else
+        echo "rspec not installed. Skipping rspec-puppet tests..."
+    fi
 fi
 
 #r10k puppetfile syntax check
 if hash r10k >/dev/null 2>&1; then
-  if [[ "$changedfile" = "Puppetfile" ]]; then
+    if [[ "$changedfile" = "Puppetfile" ]]; then
         "${subhook_root}/r10k_syntax_check.sh"
         RC=$?
         if [[ "$RC" -ne 0 ]]; then
-                failures=$((failures + 1))
+            failures=$((failures + 1))
         fi
-  fi
+    fi
 else
     echo "r10k not installed. Skipping r10k Puppetfile test..."
 fi
